[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "i3astropy"
readme = "README.md"
requires-python = "~=3.7"
license = {file = "LICENCE"}
authors = [{name = "Kevin Meagher"}]
keywords = ["python", "science", "astronomy", "astrophysics", "astropy", "IceCube", "neutrino"]
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Scientific/Engineering :: Astronomy',
    'Topic :: Scientific/Engineering :: Physics',
    ]
dependencies = ["astropy"]
dynamic = ["version", "description"]

[project.urls]
Source = "https://github.com/icecube/i3astropy"
Collaboration = "https://icecube.wisc.edu"

[project.optional-dependencies]
test = ["pytest-cov", "pytest-isort", "pytest-black", "pytest-flake8", "pytest-pylint", "flake8~=4"]

[tool.pytest.ini_options]
testpaths = ["i3astropy", "tests", "README.md"]
addopts = "--isort --black --flake8 --pylint --cov=i3astropy --pylint-ignore=tests --doctest-glob='README.md'"
flake8-max-line-length = 108
flake8-ignore = "E203, W503, F401"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 108

[tool.black]
line-length = 108
target-version = ['py37']

[tool.pylint.messages_control]
disable = "C0330, C0326, C0114, E0611"

[tool.pylint.format]
max-line-length = "108"
