name: Tests
on: [push, pull_request]
jobs:
  Tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with: {python-version: '3.7'}
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - uses: actions/setup-python@v2
      with: {python-version: '3.9'}
    - uses: actions/setup-python@v2
      with: {python-version: '3.10'}
    - name: Tests
      run: |
        pip install tox
        tox
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        verbose: true
